owner: get-gpt
repo: upptime

sites:
  - name: Get ChatGPT Home Page
    url: https://getgptapi.com
    method: GET
    headers:
      - "User-Agent: GitHub Action"
    maxResponseTime: 2000
  - name: Get ChatGPT Chat Online
    url: https://chat.getgptapi.com
    method: GET
    headers:
      - "User-Agent: GitHub Action"
    maxResponseTime: 2000
  - name: Get ChatGPT - Backend API
    url: https://i.getgptapi.com/api/v1/ping
    method: GET
    headers:
      - "User-Agent: GitHub Action"
    maxResponseTime: 2000
  - name: Domain - Global Proxy
    url: https://api.getgptapi.com/api/v1/ping
    method: GET
    headers:
      - "User-Agent: GitHub Action"
    maxResponseTime: 2000
  - name: Domain - us-e154412c.getgptapi.com
    url: https://us-e154412c.getgptapi.com/api/v1/ping
    method: GET
    headers:
      - "User-Agent: GitHub Action"
    maxResponseTime: 2000
  - name: Domain - us-d8c90975.getgptapi.com
    url: https://us-d8c90975.getgptapi.com/api/v1/ping
    method: GET
    headers:
      - "User-Agent: GitHub Action"
    maxResponseTime: 2000
  - name: Get ChatGPT - Pure Proxy
    url: https://proxy.getgptapi.com/v1/models
    method: GET
    headers:
      - "User-Agent: GitHub Action"
    maxResponseTime: 2000
  - name: Get ChatGPT - Pure Proxy 1
    url: https://proxy-1.getgptapi.com/v1/models
    method: GET
    headers:
      - "User-Agent: GitHub Action"
    maxResponseTime: 2000
  - name: Get ChatGPT - Pure Proxy 2
    url: https://proxy-2.getgptapi.com/v1/models
    method: GET
    headers:
      - "User-Agent: GitHub Action"
    maxResponseTime: 2000

workflowSchedule:
  graphs: "5 * * * *"
  responseTime: "0 * * * *"
  staticSite: "0 1 * * *"
  summary: "5 * * * *"
  updateTemplate: "0 0 * * *"
  updates: "5 * * * *"
  uptime: "*/5 * * * *"

status-website:
  cname: status.getgptapi.com
  logoUrl: https://getgptapi.com/logo.png
  favicon: https://getgptapi.com/logo.png
  name: Status
  introTitle: "Status of Get ChatGPT"
  introMessage: The Status Page which uses **real-time** data from our [GitHub repository](https://github.com/get-gpt/upptime).
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO
